/// §9.T3: Validate that `make pkg` infrastructure exists: Makefile has pkg target,
/// packaging scripts exist, LaunchAgent plist is present.
/// Full end-to-end `make pkg` test is in manual test §9.T4.

use std::path::PathBuf;

fn project_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

#[test]
fn makefile_has_pkg_target() {
    let makefile = project_root().join("Makefile");
    assert!(makefile.exists(), "Makefile must exist");
    let content = std::fs::read_to_string(&makefile).unwrap();
    assert!(content.contains("pkg:"), "Makefile must have pkg: target");
    assert!(content.contains("pkgbuild"), "pkg target must use pkgbuild");
}

#[test]
fn packaging_postinstall_script_is_executable_and_correct() {
    let postinstall = project_root().join("packaging/postinstall");
    assert!(postinstall.exists(), "packaging/postinstall must exist");

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mode = std::fs::metadata(&postinstall).unwrap().permissions().mode();
        assert!(mode & 0o111 != 0, "postinstall must be executable");
    }

    let content = std::fs::read_to_string(&postinstall).unwrap();
    assert!(content.contains("security add-trusted-cert"), "postinstall must install CA");
    assert!(content.contains("privacyclaw"), "postinstall must reference privacyclaw");
}

#[test]
fn launch_agent_plist_exists() {
    // LaunchAgent plist — may be in packaging/ or generated by the Makefile
    let candidates = [
        project_root().join("packaging/com.privacyclaw.proxy.plist"),
        project_root().join("packaging/launchagent.plist"),
    ];
    let found = candidates.iter().any(|p| p.exists());
    assert!(found, "LaunchAgent plist must exist in packaging/; candidates: {:?}", candidates);
}

#[test]
fn dist_dir_referenced_in_makefile() {
    let makefile = project_root().join("Makefile");
    let content = std::fs::read_to_string(&makefile).unwrap();
    // The pkg target must produce a .pkg file in the dist directory
    assert!(content.contains(".pkg"), "Makefile must produce a .pkg file");
    assert!(content.contains("dist/") || content.contains("$(DIST)"), "output must go to dist/ directory");
}

#[test]
fn makefile_pkg_layout_copies_sidecar() {
    let makefile = project_root().join("Makefile");
    let content = std::fs::read_to_string(&makefile).unwrap();
    assert!(
        content.contains("privacyclaw-slm-sidecar"),
        "Makefile _pkg-layout must copy privacyclaw-slm-sidecar to SHARE_DIR"
    );
}

#[test]
fn makefile_has_tarball_target() {
    let makefile = project_root().join("Makefile");
    let content = std::fs::read_to_string(&makefile).unwrap();
    assert!(content.contains("tarball:"), "Makefile must have tarball: target");
    assert!(content.contains("LLAMA_CPP_TAG"), "Makefile must declare LLAMA_CPP_TAG");
    assert!(content.contains("print-llama-tag"), "Makefile must have print-llama-tag target");
    assert!(content.contains("tap-sync-formula"), "Makefile must have tap-sync-formula target");
}
